<?php

namespace Tests\Unit;

use App\Models\OrderStatus;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class OrderStatusTest extends TestCase
{
    use DatabaseMigrations;

    public function testItHasExpectedColumns(): void
    {
        $this->assertTrue(
            Schema::hasColumns('order_statuses', [
                'id',
                'uuid',
                'title',
                'created_at',
                'updated_at'
            ])
        );
    }

    public function testUUIDIsAutoGeneratedOnSave(): void
    {
        $orderStatus = new OrderStatus();
        $orderStatus->title = 'My Order Status';
        $orderStatus->save();

        $this->assertNotEmpty($orderStatus->uuid);
        $this->assertIsString($orderStatus->uuid);
    }
}
