<?php

namespace Tests\Unit;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class UserTest extends TestCase
{
    use DatabaseMigrations;

    public function testItHasExpectedColumns(): void
    {
        $this->assertTrue(
            Schema::hasColumns('users', [
                'id',
                'uuid',
                'first_name',
                'last_name',
                'is_admin',
                'email',
                'email_verified_at',
                'password',
                'avatar',
                'address',
                'phone_number',
                'is_marketing',
                'created_at',
                'updated_at',
                'last_login_at'
            ])
        );
    }

    public function testUUIDIsAutoGeneratedOnSave(): void
    {
        $user = User::factory()->make()->toArray();

        $user = User::create(array_merge($user, ['password' => '123456']));

        $this->assertNotEmpty($user->uuid);
        $this->assertIsString($user->uuid);
    }
}
